version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: music-ai-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: music-ai-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/musicai?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  ml-api:
    build: ./ml-api
    container_name: music-ai-ml
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./ml-api:/app
      - ./ml-api/lora_models:/app/lora_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build: .
    container_name: music-ai-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_ML_API_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongodb_data: