[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd ml-api && python lightweight_main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
PYTHONPATH = "/app/ml-api"